baseURL: https://recipes.lane.sh
disablePathToLower: true
languageCode: en-us
title: Lane Recipes
theme: gochowdown
languagecode: en
googleAnalytics: 
defaultcontentlanguage: en
paginate: 10
canonifyurls: true
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsOptions: "linenos=table"
permalinks:
  posts: /posts/:year/:month/:title
params:
  author: The Lanes
  description: Recipes used by the Lane family
  keywords: 'recipes'
  favicon_32: /images/favicon-32x32.png
  favicon_16: /images/favicon-16x16.png
  footercontent: 
  hidecredits: false
  hidecopyright: false
  custom_css: 
    - style.css
menu:
  main:
    - name: Home
      weight: 1
      url: /
    - name: Resume
      weight: 2
      url: /resume/
    - name: Posts
      weight: 3
      url: /posts/
